// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB07_UlELw9Govdxek6ioD6gNCsvumHmHg',
    appId: '1:383976914048:web:63b64c80352b1482e8ba65',
    messagingSenderId: '383976914048',
    projectId: 'amen-b2dc0',
    authDomain: 'amen-b2dc0.firebaseapp.com',
    storageBucket: 'amen-b2dc0.firebasestorage.app',
    measurementId: 'G-TD6JGDHD2S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEcI9UbfwAZLWg3aBm1hu3Ousg0l2zocA',
    appId: '1:383976914048:android:33ad73cda192faefe8ba65',
    messagingSenderId: '383976914048',
    projectId: 'amen-b2dc0',
    storageBucket: 'amen-b2dc0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjpCe-QN2gBrDMKIiVL-nI-Fr8KEYl4nk',
    appId: '1:383976914048:ios:c707276ff35004bbe8ba65',
    messagingSenderId: '383976914048',
    projectId: 'amen-b2dc0',
    storageBucket: 'amen-b2dc0.firebasestorage.app',
    iosBundleId: 'com.amen.amen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjpCe-QN2gBrDMKIiVL-nI-Fr8KEYl4nk',
    appId: '1:383976914048:ios:c707276ff35004bbe8ba65',
    messagingSenderId: '383976914048',
    projectId: 'amen-b2dc0',
    storageBucket: 'amen-b2dc0.firebasestorage.app',
    iosBundleId: 'com.amen.amen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB07_UlELw9Govdxek6ioD6gNCsvumHmHg',
    appId: '1:383976914048:web:22f2f87c160569b7e8ba65',
    messagingSenderId: '383976914048',
    projectId: 'amen-b2dc0',
    authDomain: 'amen-b2dc0.firebaseapp.com',
    storageBucket: 'amen-b2dc0.firebasestorage.app',
    measurementId: 'G-1PBXZXT0D4',
  );
}
